#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
@author: okabeshu
"""
from Learn import *
from Traduction import *

daf = {} # Dictionaire final
test = {} # Dictionnaire pour tester
frequence = {} # Occurence du mot dans la langue

#########################################
#                                       #
#         Lecture des fichiers          # 
#                                       #
#########################################
Anglais = open("Test_anglais.txt", "r", encoding="utf-8")
Anglais = Anglais.read()
#print(Anglais)

Francais = open("Test_francais.txt", "r", encoding="utf-8")
Francais = Francais.read()
#print(Francais)

########################################
#                                      #
#         Traitement de texte          # 
#                                      #
########################################
# Decoupage du fichier texte en phrase.
Texte_EN = phrasify (Anglais)
Texte_FR = phrasify (Francais)

# Decoupage d'une phrase en mots.
Phrase_EN = hashify_sent (phrasify(Anglais)[3])
Phrase_FR = hashify_sent (phrasify(Francais)[3])

# Remplissage du dictionnaire des fréquences
frequence = rempl_freq(Anglais)

example = "Fluffy, he ate harmoniously with sad Battgavish. Yes. Then Lotara ate two red plants, green cats."
#essai = identique (Anglais, Francais, daf, frequence) 
#print(essai)
tenter = remplissage (Anglais, Francais, daf)
tenta = corresp_1(Anglais, Francais, tenter)
#print(tenta)
test = tenta.copy()
tr = motamot (Anglais, tenta)
print(tr)
#essai = unitsup(Phrase_EN, Phrase_FR, test)
#print(essai)

dic_sur, dic_hyp, fre = complete (Anglais, Francais, daf)

# print(paragraphy(phrasify(Anglais)))

