#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
@author: okabeshu
"""
from Learn import *

from Traduction import *

#########################################
#                                       #
#         Lecture des fichiers          # 
#                                       #
#########################################
# Test
Anglais = open("Test_anglais.txt", "r", encoding="utf-8")
Anglais = Anglais.read()
Francais = open("Test_francais.txt", "r", encoding="utf-8")
Francais = Francais.read()

# Court
Court_en = open("Court_en.txt", "r", encoding="utf-8")
Court_en = Court_en.read()
Court_fr = open("Court_fr.txt", "r", encoding="utf-8")
Court_fr = Court_fr.read()

# Rossignol
Nightingale = open("Nightingale Rose.txt", "r", encoding="utf-8")
Nightingale = Nightingale.read()
Rossignol = open("Rossignol Rose.txt", "r", encoding="utf-8")
Rossignol = Rossignol.read()

# Chansons
Songs = open("Songs.txt", "r", encoding="utf-8")
Songs = Songs.read()
Chansons = open("Chansons.txt", "r", encoding="utf-8")
Chansons = Chansons.read()

# The Beatles
Beatles_EN = open("Beatles_EN.txt", "r", encoding="utf-8")
Beatles_EN = Beatles_EN.read()
Beatles_FR = open("Beatles_FR.txt", "r", encoding="utf-8")
Beatles_FR = Beatles_FR.read()

# Yesterday
Yesterday = open("Yesterday.txt", "r", encoding="utf-8")
Yesterday = Yesterday.read()
Hier = open("Hier.txt", "r", encoding="utf-8")
Hier = Hier.read()

# Hello, Goodbye
Hello = open("Hello.txt", "r", encoding="utf-8")
Hello = Hello.read()
Bonjour = open("Bonjour.txt", "r", encoding="utf-8")
Bonjour = Bonjour.read()

# Adele
Adele_en = open("Adele_en.txt", "r", encoding="utf-8")
Adele_en = Adele_en.read()
Adele_fr = open("Adele_fr.txt", "r", encoding="utf-8")
Adele_fr = Adele_fr.read()

# The Economist
Economist_EN = open("Economist_EN.txt", "r", encoding="utf-8")
Economist_EN = Economist_EN.read()
Economist_FR = open("Economist_FR.txt", "r", encoding="utf-8")
Economist_FR = Economist_FR.read()


fre = {}
daf = {}

################################################
#                                              #
#         Remplissage du dictionnaire          # 
#                                              #
################################################
# Remplir le dictionnaire pour les traductions.
# Mais avec quels textes ?
def rempl_dic (daf, freq, n, quels) : 
    # quels : liste de booléens
    for i in range (n) : 
        if quels[0] :
            ajout_texte (Anglais, Francais, daf, freq)
        if quels[1] : 
            for j in range (2) : 
                ajout_texte (Court_en, Court_fr, daf, freq)
        if quels[2] :
            ajout_texte (Beatles_EN, Beatles_FR, daf, freq)
            #ajout_texte (Yesterday, Hier, daf, freq)
            #ajout_texte (Hello, Bonjour, daf, freq)
        if quels[3] :
            ajout_texte (Adele_en, Adele_fr, daf, freq)
        #if quels[4] :
            #ajout_texte (Economist_EN, Economist_FR, daf, freq)
        print(i)
    f = freq_hyp(daf)
    daf = mauvaise_trad (daf, f, 0.1)
    return daf, freq
 
#####################
#       Tests       #
#####################
#rempl_dic (daf, fre, 2, [False, True, True, False])

#################################################
#                                               #
#         Amélioration du dictionnaire          # 
#                                               #
#################################################
# Amélioration du dictionnaire pour les traductions.
# Mais avec quels textes ?
from Traduction import *

def ameliore_dic (daf, n, quels) : 
    # quels : liste de booléens
    dico = deepcopy(daf)
    for i in range (n) : 
        if quels[0] :
            dico = retro (Anglais, Francais, dico)
        if quels[1] : 
            for j in range (2) : 
                dico = retro (Court_en, Court_fr, daf)
        if quels[2] :
            #dico = retro (Beatles_EN, Beatles_FR, daf)
            dico = retro (Yesterday, Hier, daf)
            dico = retro (Hello, Bonjour, daf)
        if quels[3] :
            dico = retro (Adele_en, Adele_fr, daf)
        if quels[4] :
            dico = retro (Economist_EN, Economist_FR, daf)
        print(i)
    f = freq_hyp(dico)
    daf = mauvaise_trad (dico, f, 0.1)
    return dico
 
#ameliore_dic (daf, 2, [False, True, True, False])


